# -*- coding: utf-8 -*-
"""public_holiday.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zc9c1XfdzW3UBOiHr5axNE6R2KftChiA
"""

import json
import requests
import pandas as pd 

class Fetch_Public_Holidays:
    def __init__(self, base_url):
        """Initialize the Public Holiday fetcher instance"""
        self.base_url = base_url
        self.public_holidays = list()
        self.alberta_holidays = list()
        self.ab_county_name = 'CA-AB'

    def fetch_data(self, year, country):
        """A method to fetch a list of public holidays from a specific year and country.

        year: Use string format in numbers.
        params: Use standard country abbreviation (CA for Canada).
        """
        url = f"{self.base_url}/{year}/{country}"
        response = requests.get(url)
        self.public_holidays = json.loads(response.content)
        return self.public_holidays

    def filter_out_alberta_holidays(self):
        """Filters out holidays specific to Alberta from the fetched public holidays."""
        self.alberta_holidays.clear()
        for holiday in self.public_holidays:
            if holiday['counties'] is None:
                self.alberta_holidays.append(holiday)
            else:
                for county in holiday['counties']:
                    if county == self.ab_county_name:
                        self.alberta_holidays.append(holiday)
        return pd.DataFrame(self.alberta_holidays)
        
    def fetch_and_combine_holidays(self, start_year, end_year, country):
        """Fetch and combine all Alberta holidays across a range of years."""
        holidays_df = pd.DataFrame()

        for year in range(start_year, end_year+1):
            # fetch data for Canada in a specific year
            self.fetch_data(str(year), country)
            # filter out Alberta holidays from the fetched data
            alberta_holidays = self.filter_out_alberta_holidays()
            # append all the holidasy to the Dataframe
            holidays_df = pd.concat([holidays_df, alberta_holidays], ignore_index=True)
        
        return holidays_df