# Generated by Django 5.0.3 on 2024-04-17 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iris_predict_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='predresults',
            options={'verbose_name_plural': 'Pred results'},
        ),
    ]
